DEL "%CATALINA_HOME%\webapps\%SOURCE_WAR_NAME%" >> %INTEGRATION_HOME%\%LOG_FILE%
RMDIR /Q /S "%CATALINA_HOME%\webapps\%SOURCE_NAME%" >> %INTEGRATION_HOME%\%LOG_FILE%
COPY target\%SOURCE_WAR_NAME% "%CATALINA_HOME%\webapps\%SOURCE_WAR_NAME%" >> %INTEGRATION_HOME%\%LOG_FILE%
ECHO War copied.