ECHO mvn build ...
ECHO /---------- MVN build -----------/ >> %INTEGRATION_HOME%\%LOG_FILE%
CALL mvn clean install >> %INTEGRATION_HOME%\%LOG_FILE%
ECHO /--------------------------------/ >> %INTEGRATION_HOME%\%LOG_FILE%
ECHO >> %INTEGRATION_HOME%\%LOG_FILE%

IF NOT EXIST target\%SOURCE_WAR_NAME% (
	ECHO ERROR : %SOURCE_WAR_NAME% BUILD FAILED >> %INTEGRATION_HOME%\%LOG_FILE%
	EXIT 1
)
ECHO INFO : %SOURCE_WAR_NAME% BUILD SUCCESS >> %INTEGRATION_HOME%\%LOG_FILE%