#!/usr/bin/env bash
echo
echo // ----- Copying war

rm "$CATALINA_HOME/webapps/$SOURCE_WAR_NAME" >> "$INTEGRATION_HOME/$LOG_FILE" 2>> "$INTEGRATION_HOME/$LOG_FILE"
rm -rf "$CATALINA_HOME/webapps/$SOURCE_NAME" >> "$INTEGRATION_HOME/$LOG_FILE" 2>> "$INTEGRATION_HOME/$LOG_FILE"
cp "target/$SOURCE_WAR_NAME" "$CATALINA_HOME/webapps/$SOURCE_WAR_NAME" >> "$INTEGRATION_HOME/$LOG_FILE" 2>> "$INTEGRATION_HOME/$LOG_FILE"
