CLS
@ECHO OFF

ECHO Configurations.
set datetimef=%date:~-4%_%date:~3,2%_%date:~0,2%__%time:~0,2%_%time:~3,2%_%time:~6,2%
SET LOG_FILE=%datetimef%.log
SET SOURCE_MODULE_RELATIVE_PATH=..\..\..\fakeDataSource
SET RESOURCES_RELATIVE_PATH=..\resources
SET SOURCE_WAR_NAME=fakeDataSource.war

SET "INTEGRATION_HOME=%CD%"
ECHO INTEGRATION_HOME : %INTEGRATION_HOME% > %INTEGRATION_HOME%\%LOG_FILE%

ECHO /---------- Working Configurations -----------/ >> %INTEGRATION_HOME%\%LOG_FILE%
ECHO SOURCE_MODULE_RELATIVE_PATH = %SOURCE_MODULE_RELATIVE_PATH% >> %INTEGRATION_HOME%\%LOG_FILE%
ECHO RESOURCES_RELATIVE_PATH = %RESOURCES_RELATIVE_PATH% >> %INTEGRATION_HOME%\%LOG_FILE%
ECHO /---------------------------------------------/ >> %INTEGRATION_HOME%\%LOG_FILE%
ECHO >> %INTEGRATION_HOME%\%LOG_FILE%


CD %SOURCE_MODULE_RELATIVE_PATH%
ECHO mvn build ...
CALL mvn clean install >> %INTEGRATION_HOME%\%LOG_FILE%
ECHO >> %INTEGRATION_HOME%\%LOG_FILE%

IF NOT EXIST target\%SOURCE_WAR_NAME% (
	ECHO ERROR : %SOURCE_WAR_NAME% BUILD FAILED
	EXIT 1
)
ECHO INFO : %SOURCE_WAR_NAME% BUILD SUCCESS >> %INTEGRATION_HOME%\%LOG_FILE%

COPY target\%SOURCE_WAR_NAME% %INTEGRATION_HOME%\%RESOURCES_RELATIVE_PATH% >> %INTEGRATION_HOME%\%LOG_FILE%
ECHO War copied.

:: call mvn test -DskipTests=false



:: END

CD %INTEGRATION_HOME%
