CLS
@ECHO OFF

SET "INTEGRATION_HOME=%CD%"
ECHO INTEGRATION_HOME : %INTEGRATION_HOME% > %INTEGRATION_HOME%\%LOG_FILE%


CALL %INTEGRATION_HOME%\configurations.bat
CALL %INTEGRATION_HOME%\checkEnvironment.bat
CALL %INTEGRATION_HOME%\stopTomcat.bat
CALL %INTEGRATION_HOME%\startTomcat.bat

CD %SOURCE_MODULE_RELATIVE_PATH%

CALL %INTEGRATION_HOME%\mvnBuild.bat
CALL %INTEGRATION_HOME%\cpyWar.bat

CD %INTEGRATION_HOME%

CALL %INTEGRATION_HOME%\waitTomcat.bat
CALL %INTEGRATION_HOME%\checkTomcat.bat

CALL %INTEGRATION_HOME%\startActiveMQ.bat

CALL %INTEGRATION_HOME%\waitActiveMQ.bat
CALL %INTEGRATION_HOME%\checkActiveMQ.bat

CALL %INTEGRATION_HOME%\stopActiveMQ.bat
CALL %INTEGRATION_HOME%\stopTomcat.bat
